novel:
	QUERY="变性 filetype:txt" node search_wait.js
	QUERY="阉割 filetype:txt" node search_wait.js
	QUERY="性转 filetype:txt" node search_wait.js
	QUERY="变性 小说 filetype:pdf" node search_wait.js
	QUERY="伪娘 小说 filetype:txt" node search_wait.js
	QUERY="性转 漫画 filetype:pdf" node search_wait.js
	QUERY="跨性别 漫画 filetype:pdf" node search_wait.js
	QUERY="伪娘 漫画 filetype:pdf" node search_wait.js
	QUERY="性转 小说 filetype:pdf" node search_wait.js
	QUERY="变性 漫画 filetype:pdf" node search_wait.js
	QUERY="变性 小说 filetype:pdf" node search_wait.js
