website:
	QUERY="site:news.sina.cn 变性" node search.js
	QUERY="site:news.ifeng.com 变性" node search.js
	QUERY="site:m.thepaper.cn 变性 跨性别" node search.js
	QUERY="site:people.com.cn 变性手术" node search.js
	QUERY="site:xinhuanet.com 跨性别 变性" node search.js
	QUERY="site:chinanews.com.cn 变性人" node search.js
	QUERY="site:chinanews.com.cn 跨性别" node search.js

xyn_news:
	QUERY="药娘 新闻" node search.js
	QUERY="性别重置手术 新闻" node search.js
	QUERY="跨性别 药 新闻" node search.js
	
trans_news:
	QUERY="变性手术 男 新闻" node search_wait.js
	QUERY="易性癖 新闻" node search_wait.js
	QUERY="易性癖 filetype:pdf" node search_wait.js
	QUERY="易性癖 filetype:pdf" node search_wait.js
	QUERY="性别认同障碍 filetype:pdf" node search.js

trans:
	QUERY="性别认同障碍" node search.js
	QUERY="性别多元化" node search.js
	QUERY="跨性别 青少年" node search.js
	QUERY="跨性别 切除" node search.js
	QUERY="男跨女" node search.js
	QUERY="女跨男" node search.js
	QUERY="酷儿 新闻" node search.js

novel:
	QUERY="变性 小说 filetype:txt" node search_wait.js
	QUERY="阉割 小说 filetype:txt" node search_wait.js
	QUERY="性转 小说 filetype:txt" node search_wait.js
	QUERY="变性 小说 filetype:pdf" node search_wait.js
	QUERY="伪娘 小说 filetype:txt" node search_wait.js
	QUERY="性转 漫画 filetype:pdf" node search_wait.js
	QUERY="跨性别 漫画 filetype:pdf" node search_wait.js
	QUERY="伪娘 漫画 filetype:pdf" node search_wait.js
	QUERY="性转 小说 filetype:pdf" node search_wait.js
	QUERY="变性 漫画 filetype:pdf" node search_wait.js
	QUERY="变性 小说 filetype:pdf" node search_wait.js
