novel:
	QUERY="酷儿 filetype:pdf" node search_wait.js
	QUERY="多元性别 filetype:pdf" node search_wait.js

date:
	QUERY="变性人 before:2000-12-31" node search_wait.js
	QUERY="变性人 after:2001-01-01 before:2001-12-31" node search_wait.js
	QUERY="变性人 after:2002-01-01 before:2002-12-31" node search_wait.js
	QUERY="变性人 after:2003-01-01 before:2003-12-31" node search_wait.js
	QUERY="变性人 after:2004-01-01 before:2004-12-31" node search_wait.js
	QUERY="变性人 after:2005-01-01 before:2005-12-31" node search_wait.js
	QUERY="变性人 after:2006-01-01 before:2006-12-31" node search_wait.js

	QUERY="准变性人 before:2008-12-31" node search_wait.js
	QUERY="变性手术 before:2009-12-31" node search_wait.js

	QUERY="变性人 site:news.sina.com.cn before:2006-12-31" node search_wait.js
	QUERY="变性人 site:www.chinanews.com/ before:2006-12-31" node search_wait.js
	QUERY="变性人 site:news.sohu.com/ before:2006-12-31" node search_wait.js


date_news:
	QUERY="变性 新闻 before:2000-12-31" node search_wait.js
	QUERY="变性 新闻 after:2001-01-01 before:2001-12-31" node search_wait.js
	QUERY="变性 新闻 after:2002-01-01 before:2002-12-31" node search_wait.js
	QUERY="变性 新闻 after:2003-01-01 before:2003-12-31" node search_wait.js
	QUERY="变性 新闻 after:2004-01-01 before:2004-12-31" node search_wait.js
	QUERY="变性 新闻 after:2005-01-01 before:2005-12-31" node search_wait.js
	QUERY="变性 新闻 after:2006-01-01 before:2006-12-31" node search_wait.js
