base:
	python serper.py "异装癖" --pages 3
	python serper.py "易性癖" --pages 3
	python serper.py "变性人" --pages 3
	python serper.py "跨性别" --pages 3
	python serper.py "人妖" --pages 3
	python serper.py "药娘" --pages 3
	python serper.py "两性畸形" --pages 3
	python serper.py "性别认同障碍" --pages 3
	python serper.py "双性人" --pages 3
	python serper.py "性别重置手术" --pages 3
	python serper.py "变性手术" --pages 3
	python serper.py "人妖手术" --pages 3
	python serper.py "人妖 激素" --pages 3
	python serper.py "跨性别 激素" --pages 3
	python serper.py "变性 激素" --pages 3
	python serper.py "性别焦虑症" --pages 3
	python serper.py "性别平权" --pages 3
	python serper.py "变性 文化差异" --pages 3
	python serper.py "跨性别 社会接纳" --pages 3
	python serper.py "跨性别 争议" --pages 3
	python serper.py "变性 支持团体" --pages 3
	python serper.py "跨性别 偏见" --pages 3
	python serper.py "跨性别 社会压力" --pages 3
	python serper.py "跨性别 歧视" --pages 3
	python serper.py "跨性别 性别表达" --pages 3
	python serper.py "非二元性别" --pages 3
	python serper.py "性别酷儿" --pages 3
	python serper.py "性别流动" --pages 3
	python serper.py "泛性别" --pages 3
	python serper.py "中性别" --pages 3
	python serper.py "无性别" --pages 3
	python serper.py "性别解构" --pages 3
	python serper.py "性别认同光谱" --pages 3
	python serper.py "性别赋权" --pages 3
	python serper.py "性别解放" --pages 3
	python serper.py "异性模仿" --pages 3
	python serper.py "性别延展" --pages 3
	python serper.py "异装角色扮演" --pages 3
	python serper.py "流动性别" --pages 3
	python serper.py "性别探索" --pages 3
	python serper.py "社会性别分布" --pages 3
	python serper.py "自我性别意识" --pages 3
	python serper.py "性别二元论" --pages 3
	python serper.py "非典型性别" --pages 3
	python serper.py "变装艺术" --pages 3
	python serper.py "男性女性化" --pages 3
	python serper.py "女性男性化" --pages 3
	python serper.py "娘娘腔" --pages 3
	python serper.py "娘炮" --pages 3
	python serper.py "娘炮 文化" --pages 3
	python serper.py "娘炮 现象" --pages 3

minority:
	python serper.py "性转" --pages 3
	python serper.py "CD 角色扮演" --pages 3
	python serper.py "TS 文化" --pages 3
	python serper.py "TS AG 是什么" --pages 3
	python serper.py "伪娘文化" --pages 3
	python serper.py "伪娘圈" --pages 3
	python serper.py "性转圈" --pages 3
	python serper.py "Trans 文化" --pages 3
	python serper.py "跨性别幻想" --pages 3
	python serper.py "性转同人" --pages 3
	python serper.py "变装派对" --pages 3
	python serper.py "CD/TG社群" --pages 3
	python serper.py "伪街" --pages 3
	python serper.py "伪街 CD" --pages 3
	python serper.py "伪街 CD" --pages 3
	python serper.py "男娘" --pages 3
	python serper.py "伪娘" --pages 3
	python serper.py "男娘 二次元" --pages 3
	python serper.py "伪娘 二次元" --pages 3
	python serper.py "药娘 二次元" --pages 3
	python serper.py "女装 二次元" --pages 3
	python serper.py "女装子" --pages 3
	python serper.py "女装 男性" --pages 3
	python serper.py "男扮女装" --pages 3
	python serper.py "女扮男装" --pages 3
	python serper.py "娘化" --pages 3
	python serper.py "伪娘 COS" --pages 3
	python serper.py "可爱的男孩子" --pages 3
	python serper.py "女装大佬" --pages 3
	python serper.py "变装 CD" --pages 3

	# 小众身份和非主流性别认同
	python serper.py "泛性别认同" --pages 3
	python serper.py "非传统性别" --pages 3
	python serper.py "多重性别" --pages 3
	python serper.py "性别表达障碍" --pages 3
	python serper.py "跨性别二元论" --pages 3
	python serper.py "多元性别认同" --pages 3

	# 针对跨性别群体的小众医疗术语
	python serper.py "跨性别激素替代疗法" --pages 3
	python serper.py "性别肯定治疗" --pages 3
	python serper.py "性别确认过程" --pages 3
	python serper.py "自我认同性别确认" --pages 3
	python serper.py "跨性别干预措施" --pages 3
	python serper.py "性别表达支持" --pages 3
	python serper.py "变性抑郁支持" --pages 3
	python serper.py "跨性别行为疗法" --pages 3

	# 跨性别与变装的次文化和亚文化词汇
	python serper.py "异装圈" --pages 3
	python serper.py "异装者次文化" --pages 3
	python serper.py "性别模糊角色" --pages 3
	python serper.py "异性模仿秀" --pages 3
	python serper.py "性别反转角色" --pages 3
	python serper.py "异性反串" --pages 3

	# 其他专业术语
	python serper.py "性别悖论" --pages 3
	python serper.py "性别脱敏" --pages 3
	python serper.py "社会性别自我定位" --pages 3
	python serper.py "性别错置感" --pages 3
	python serper.py "自我性别矫正" --pages 3
	python serper.py "性别二元偏见" --pages 3
	python serper.py "性别表达策略" --pages 3
	python serper.py "异性反串表演" --pages 3
	python serper.py "性别边缘文化" --pages 3
	python serper.py "社会性别错位" --pages 3
	python serper.py "跨性别赋权" --pages 3

news:
	python serper.py "跨性别 中国 新闻" --pages 3
	python serper.py "变性 新浪新闻" --pages 3
	python serper.py "变性 新闻" --pages 3
	python serper.py "药娘 新闻" --pages 3
	python serper.py "药娘 新浪新闻" --pages 3
	python serper.py "人妖 新闻" --pages 3
	python serper.py "人妖 中国" --pages 3
	python serper.py "跨性别 澎湃新闻" --pages 3
	python serper.py "两性畸形 新闻" --pages 3
	python serper.py "双性人 新闻" --pages 3
	python serper.py "异装癖 新闻" --pages 3

story:
	python serper.py "变性 故事" --pages 3
	python serper.py "人妖 故事" --pages 3
	python serper.py "药娘 故事" --pages 3
	python serper.py "易性癖 故事" --pages 3
	python serper.py "跨性别 故事" --pages 3
	python serper.py "异装癖 故事" --pages 3
	python serper.py "跨性别 故事" --pages 3
	python serper.py "变性人 故事" --pages 3
	python serper.py "双性人 故事" --pages 3
	python serper.py "两性畸形 故事" --pages 3

novel:
	python serper.py "变性 小说" --pages 3
	python serper.py "人妖 小说" --pages 3
	python serper.py "性转 小说" --pages 3
	python serper.py "变装 小说" --pages 3
	python serper.py "CDTS 小说" --pages 3
	python serper.py "TS 小说" --pages 3
	python serper.py "跨性别 小说" --pages 3
	python serper.py "双性人 小说" --pages 3
	python serper.py "伪娘 小说" --pages 3
	python serper.py "男娘 小说" --pages 3
	python serper.py "男娘 小说" --pages 3
	python serper.py "伪娘 小说" --pages 3
	python serper.py "男娘 轻小说" --pages 3
	python serper.py "伪娘 轻小说" --pages 3
	python serper.py "药娘 轻小说" --pages 3
	python serper.py "女装 轻小说" --pages 3
	python serper.py "男扮女装 轻小说" --pages 3
	python serper.py "娘化 轻小说" --pages 3
	python serper.py "女装大佬 轻小说" --pages 3
	python serper.py "变身 小说" --pages 3
	python serper.py "变身 文" --pages 3
	python serper.py "变身 百合" --pages 3
	python serper.py "变百" --pages 3
	python serper.py "变嫁" --pages 3

platform:
	python serper.py "跨性别 豆瓣" --pages 3
	python serper.py "易性癖 豆瓣" --pages 3
	python serper.py "变性人 豆瓣" --pages 3
	python serper.py "异装癖 豆瓣" --pages 3
	python serper.py "跨性别 知乎" --pages 3
	python serper.py "跨性别 微博" --pages 3
	python serper.py "跨性别 搜狐" --pages 3
	python serper.py "人妖 豆瓣" --pages 3
	python serper.py "夏士莲" --pages 3

legal:
	python serper.py "跨性别 法律" --pages 3
	python serper.py "跨性别 权利 中国" --pages 3
	python serper.py "跨性别 政策 中国" --pages 3
	python serper.py "性别重置 法律 中国" --pages 3
	python serper.py "变性 手术 法律" --pages 3
	python serper.py "两性畸形 法律" --pages 3

medical:
	python serper.py "变性 手术 医院" --pages 3
	python serper.py "变性 手术 医生" --pages 3
	python serper.py "变性 411" --pages 3
	python serper.py "变性 长海医院" --pages 3
	python serper.py "变性 华西" --pages 3
	python serper.py "变性 北医三院" --pages 3
	python serper.py "跨性别 北医三院" --pages 3
	python serper.py "跨性别 北医六院" --pages 3
	python serper.py "跨性别 上海精神卫生中心" --pages 3
	python serper.py "跨性别 医学" --pages 3
	python serper.py "变性 心理支持" --pages 3
	python serper.py "人妖 手术" --pages 3
	python serper.py "人妖 医院" --pages 3
	python serper.py "人妖 药物" --pages 3
	python serper.py "跨性别 心理健康" --pages 3
	python serper.py "变性 保险 覆盖" --pages 3
	python serper.py "性别认同障碍 治疗" --pages 3
	python serper.py "性别焦虑" --pages 3
	python serper.py "跨性别 嗓音训练" --pages 3
	python serper.py "跨性别 面部女性化" --pages 3
	python serper.py "变性 整容" --pages 3
	python serper.py "变性 隆胸" --pages 3
	python serper.py "雌激素" --pages 3
	python serper.py "雄激素" --pages 3
	python serper.py "性激素" --pages 3
	python serper.py "性激素 药物" --pages 3
	python serper.py "雌二醇" --pages 3
	python serper.py "睾酮" --pages 3
	python serper.py "孕酮" --pages 3
	python serper.py "补佳乐" --pages 3

people:
	python serper.py "跨性别 名人" --pages 3
	python serper.py "跨性别 艺术家 中国" --pages 3
	python serper.py "跨性别 活动家" --pages 3
	python serper.py "跨性别 代表人物" --pages 3
	python serper.py "跨性别 社交媒体影响者" --pages 3


culture:
	python serper.py "跨性别 社会接受度" --pages 3
	python serper.py "跨性别 社会现象" --pages 3
	python serper.py "跨性别 文化 中国" --pages 3
	python serper.py "跨性别 社会问题" --pages 3
	python serper.py "变性 中国 文化" --pages 3

academic:
	python serper.py "跨性别 性别研究" --pages 3
	python serper.py "性别认同 研究" --pages 3
	python serper.py "变性 学术论文" --pages 3
	python serper.py "跨性别 心理学" --pages 3
	python serper.py "跨性别 社会学 研究" --pages 3
	python serper.py "多元性别 研究" --pages 3
	python serper.py "两性畸形 研究" --pages 3

art:
	python serper.py "跨性别 电影" --pages 3
	python serper.py "跨性别 文学作品" --pages 3
	python serper.py "跨性别 漫画" --pages 3
	python serper.py "性转 漫画" --pages 3
	python serper.py "性转 动漫" --pages 3
	python serper.py "伪娘 动漫" --pages 3
	python serper.py "伪娘 游戏" --pages 3
	python serper.py "男娘 动漫" --pages 3
	python serper.py "男娘 游戏" --pages 3
	python serper.py "男娘 番剧" --pages 3
	python serper.py "性转 番剧" --pages 3
	python serper.py "性转 游戏" --pages 3
	python serper.py "女装 游戏" --pages 3
	python serper.py "女装 动漫" --pages 3
	python serper.py "女装 番剧" --pages 3
	python serper.py "伪娘 番剧" --pages 3
	python serper.py "跨性别 电视剧" --pages 3
	python serper.py "跨性别 音乐作品" --pages 3
	python serper.py "跨性别 电影角色" --pages 3
	python serper.py "CDTS 艺术展览" --pages 3
	python serper.py "跨性别 文学讨论" --pages 3
	python serper.py "性别认同 电影推荐" --pages 3
	python serper.py "跨性别 诗歌" --pages 3
	python serper.py "异装 影像艺术" --pages 3
	python serper.py "人妖 艺术" --pages 3
	python serper.py "人妖 表演" --pages 3
	python serper.py "易性癖 艺术" --pages 3
	python serper.py "易性癖 表演" --pages 3

youth:
	python serper.py "跨性别 青少年" --pages 3
	python serper.py "跨性别 家庭支持" --pages 3
	python serper.py "跨性别 青少年 心理" --pages 3
	python serper.py "跨性别 家庭关系" --pages 3
	python serper.py "跨性别 青少年 教育" --pages 3

place:
	python serper.py "CDTS 中国" --pages 3
	python serper.py "跨性别 香港" --pages 3
	python serper.py "变性 香港" --pages 3
	python serper.py "跨性别 台湾" --pages 3
	python serper.py "变性 台湾" --pages 3
	python serper.py "跨性别 新加坡" --pages 3
	python serper.py "变性 新加坡" --pages 3
	python serper.py "人妖 中国" --pages 3
	python serper.py "人妖 泰国" --pages 3
	python serper.py "易性癖 中国" --pages 3

human:
	python serper.py "变性 赵烨德" --pages 3
	python serper.py "变性 何清濂" --pages 3
	python serper.py "变性 陈焕然" --pages 3
	python serper.py "变性 替迪" --pages 3

other:
	python serper.py "性转 体验" --pages 3
	python serper.py "性转 幻想" --pages 3
	python serper.py "TS 社区" --pages 3
	python serper.py "跨性别 心路历程" --pages 3
	python serper.py "性别认同 日记" --pages 3
	python serper.py "TS 文化分析" --pages 3
	python serper.py "跨性别 心理健康资源" --pages 3
	python serper.py "跨性别 团体" --pages 3
	python serper.py "跨性别 历史" --pages 3
	python serper.py "CDTS 情感" --pages 3
	python serper.py "跨性别 社区" --pages 3
	python serper.py "性别流动 现象" --pages 3
	python serper.py "非传统性别角色" --pages 3
	python serper.py "性别实验 社群" --pages 3
	python serper.py "性转 生活记录" --pages 3
	python serper.py "跨性别 日常生活" --pages 3
	python serper.py "性别身份认同 文学" --pages 3
	python serper.py "跨性别 交流" --pages 3
	python serper.py "性别认同 研究" --pages 3
	python serper.py "跨性别 访谈" --pages 3
	python serper.py "跨性别 资源" --pages 3
