novel:
	QUERY="去势 filetype:txt site:huangsewenxue.com" node search_wait.js
	QUERY="阉割 filetype:txt site:huangsewenxue.com" node search_wait.js
	QUERY="太监 filetype:txt site:huangsewenxue.com" node search_wait.js
	QUERY="阉割 女 filetype:txt site:huangsewenxue.com" node search_wait.js
	QUERY="阉奴 女 filetype:txt site:huangsewenxue.com" node search_wait.js