news:
	python .github/downloader/download/download.py --output-dir webpage_archive/raw/sina1 --download-type webpage --pattern ".*sina.*"
	python .github/downloader/download/download.py --output-dir workspace_news --download-type webpage --pattern ".*news.ifeng.*"
	python .github/downloader/download/download.py --output-dir webpage_archive/raw/ifeng.com1 --download-type webpage --pattern ".*ifeng.com.*"
	python .github/downloader/download/download.py --output-dir workspace_news --download-type webpage --pattern ".*news.*"
	python .github/downloader/download/download.py --output-dir workspace_news --download-type webpage --pattern ".*thepaper.cn.*"
	python .github/downloader/download/download.py --output-dir webpage_archive/raw/thepaper.cn1 --download-type webpage --pattern ".*thepaper.cn.*"
	python .github/downloader/download/download.py --output-dir webpage_archive/raw/sohu.com --download-type webpage --pattern ".*sohu.com.*"
	python .github/downloader/download/download.py --output-dir webpage_archive/raw/163.com --download-type webpage --pattern ".*163.com/dy.*"
	python .github/downloader/download/download.py --output-dir webpage_archive/raw/chinanews.com --download-type webpage --pattern ".*chinanews.com.*"
	python .github/downloader/download/download.py --output-dir webpage_archive/raw/news.qq.com --download-type webpage --pattern ".*news.qq.com.*"
	python .github/downloader/download/download.py --output-dir webpage_archive/raw/unclassify_news1 --download-type webpage --pattern ".*news.*"


pdf:
	python .github/downloader/download/download.py --output-dir workspace --download-type pdf --pattern ".*pdf.*"

site:
	python .github/downloader/download/download.py --output-dir webpage_archive/raw/douban.com --download-type webpage --pattern ".*douban.com.*"
	python .github/downloader/download/download.py --output-dir webpage_archive/raw/douban1.com --download-type webpage --pattern ".*(www|site|wap)\.douban\.com.*"